### PR TITLE
233 added swr and removed useEffects

### PR DESCRIPTION
**Pull request by mountclear**

### CODE REVIEW

**Comment by mountclear** [comment]
@euanwm can you check if the league submisson form works on your locally as i get cors error

**Comment by euanwm** [comment]
@mountclear Going to hold off on this as @rsbrowne has done a bunch of work that'll clash with this. I'm also changing the backend API for the main leaderboard.

**Comment by rsbrowne** [comment]
Yeah apologies, I really should have commented somewhere that I was overhauling the site to use the new App routing in Next 13

**Comment by mountclear** [comment]
@euanwm @rsbrowne 
|ok cool i'll update the PR after the update on development branch later.

**Pull request merged**
