### PR TITLE
Add db checks for best snatch, best cj, and total

### PR DESCRIPTION
**Pull request by joeysantia**
Added conditionals to check_db.py to ensure that:

1. Best snatch value is the greatest value of the snatch attempts or zero, whichever is greater
2. Best cj value is the greatest value of the cj attempts or zero, whichever is greater
3. Total is either the sum of the best snatch and cj values or zero if one of the best values is zero

### CODE REVIEW

**Comment by euanwm** [comment]
@joeysantia thanks for this, I'll get round to reviewing it tomorrow morning. It's flagged around 15k entries already so I need to investigate a few other things first.

**Review by euanwm — APPROVED** [review]
Actually, fuck it. I'll merge it now and address the knock-on issues tomorrow.

@joeysantia if you're interested in doing more then keep an eye on the issues page.

**Comment by euanwm** [comment]
Closes #334

**Comment by joeysantia** [comment]
@euanwm definitely! thanks for tagging me in those other issues -- i'll check them out

**Pull request merged**
